rl_agent:
  state_mode: 0  # 0: image, 1: laserscan
  
  # number of height cells in positive direction
  img_width_pos: 70
  # number of height cells in negative direction
  img_width_neg: 20 
  # number of height cells in negative direction
  img_height: 70 
  # resolution in m/cell
  img_resolution: 0.15
